-- Your SQL goes here
CREATE TABLE says (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    saying VARCHAR(2046) NOT NULL
);
CREATE TABLE bgimgs (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    day INTEGER NOT NULL,
    url VARCHAR(128) NOT NULL,
    UNIQUE(day)
);
