[package]
name = "initlizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = {path = "../database"}

[[bin]]
name = "initlizer"
doc = false

[lib]
doc = false
